### PR TITLE
Enable option to integrate nodesetLoader into open62541 v1.3.2

### PR DESCRIPTION
**Pull request by keba-uso**
Enabled option to build-in for integrating the **nodesetLoader** as part of the open62541 library: **_ENABLE_BUILD_INTO_OPEN62541_**. Current open62541 version supported by this option is release v1.3.2.

It is important to not that this option is not for generating a separate nodesetLoader library, rather for integrating this module as a plugin part of the open62541. Because of this, the **_ENABLE_BUILD_INTO_OPEN62541_** option should only be activated within the open62541 build (by enabling the _**UA_ENABLE_NODESETLOADER**_ flag).

Also, added a new build option: **_ENABLE_EXAMPLES_**, which handles the build of the nodesetLoader examples. This option is added in all github workflow actions. For users that want to build the examples, this option must be enabled from now on.

Also, these PR includes changes that fix the memory leak reported in #203.

**IMPORTANT:** The integration tests for the backend open62541 sub-module are disabled within the build configuration and 
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;cannot be activated in command line. All the integration tests fail for open62541 versions <=> v1.3.2. The core
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;issue behind failing integration tests, as discussed with @jpfr, could be missing support for XML-based data 
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;encoding/decoding within the open62541 library. For both the python **nodeset-compiler** and the **nodesetLoader** 
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;to generate the same output files (in integration tests), missing support for data encoding should be added. The
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;python **nodeset-compiler** already has support for decoding these data types, but by using binary data format
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;within a separate **.bsd** file included in code generation.

**TODO:** Currently, the following options are disabled within the build configuration for the built-into option: 
&emsp;&emsp;&emsp;**_ENABLE_TESTING_**, _**ENABLE_EXAMPLES**_. THis will be changed in future PRs regarding the integration with 
&emsp;&emsp;&emsp;open62541.

### CODE REVIEW

**Comment by keba-uso** [comment]
Hi @matkonnerth, I would need some support regarding failing integration tests in this pull-request.

The following integration tests failed to execute successfully:

- **IntegrationTest_DI**
- **IntegrationTest_DI_PLCOpen**
- **IntegrationTest_DI_Euromap_83_77**


I attached the the diff files between `referenceServer.txt` and `testServer.txt`:

- [DI](https://github.com/open62541/nodesetLoader/files/9664644/DI.txt)
- [DI_Euromap_83_77](https://github.com/open62541/nodesetLoader/files/9664641/DI_Euromap_83_77.txt)
- [DI_PLCopen](https://github.com/open62541/nodesetLoader/files/9664642/DI_PLCopen.txt)


For the DI nodeset, a workaruond exists to make the test pass, and that is to avoid `PrintStructureDefinition` for all data types from namespaces different from NS0:

In file: backends/open62541/tests/integration/client/[utils.cpp](https://github.com/open62541/nodesetLoader/files/9664643/utils.txt)


For the other two integration tests, issues exits with trailing spaces at the end of Node description.
Also, there are non-existing nodes within `referenceServer.txt` that could not be found inside the Nodeset XML file.

**Comment by jpfr** [comment]
Thanks for this!

Just one clarification.
Why did you choose to maintain a manual patch-set in the `nodesetLoaderDebug.patch` file?
This will break easily.

The patch-set adds debug logging.
We could add that on a permanent basis, but make it conditional on some build flag.

**Comment by keba-uso** [comment]
> Thanks for this!
> 
> Just one clarification. Why did you choose to maintain a manual patch-set in the `nodesetLoaderDebug.patch` file? This will break easily.
> 
> The patch-set adds debug logging. We could add that on a permanent basis, but make it conditional on some build flag.

This patch set was included by mistake. Yes, we could add conditional debug logs, but it will be done in another PR.

**Comment by keba-uso** [comment]
@jpfr is it possible to also merge this PR, since the [#5371](https://github.com/open62541/open62541/pull/5371) is merged and ready to use?

**Pull request merged**
